In [ ]:
#Ques-1 Print elements of array in reverse order in float formmat using numpy

import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    arr.reverse()
    return numpy.array(arr,float)

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 7 8 9 10
[10.  9.  8.  7.  3.  2.  1.]


In [ ]:
#Ques-2 Shape and Reshape

import numpy
arr = input().strip().split(' ')
my_array = numpy.array(arr,int)
print(numpy.reshape(my_array,(3,3)))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#Ques-3 Transpose and Flatten

import numpy
n, m = map(int, input().strip().split(' '))
arr = []
for i in range(n):
    arr.append(numpy.array(list(map(int, input().strip().split(' ')))))
arr = numpy.array(arr)
print(arr.transpose())
print(arr.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [ ]:
#Ques-4 Concatenate

import numpy
n, m, p = map(int, input().strip().split(' '))
arr1 = []
for i in range(n):
    arr1.append(numpy.array(list(map(int, input().strip().split(' ')))))
arr1 = numpy.array(arr1)
arr2=[]
for i in range(m):
    arr2.append(numpy.array(list(map(int, input().strip().split(' ')))))
arr2 = numpy.array(arr2)
print(numpy.concatenate((arr1, arr2), axis = 0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [ ]:
#Ques-5 Zeros and Ones

import numpy
n, m, p = map(int, input().strip().split(' '))
arr1=[]
for i in range(p):
    arr1.append(numpy.zeros((m,n), dtype = numpy.int))
arr1 = numpy.array(arr1)
print(arr1)

arr2=[]
for i in range(p):
    arr2.append(numpy.ones((m,n), dtype = numpy.int))
arr2 = numpy.array(arr2)

print(arr2)

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [ ]:
#Ques-6 Eye and Identity

import numpy
numpy.set_printoptions(legacy='1.13')
n, m = map(int, input().strip().split(' '))
print(numpy.eye(n, m, k = 0))

5 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [ ]:
#Ques-7 Array Mathematics

import numpy

n,m=map(int,input().split())
A=numpy.array([list(map(int,input().split())) for i in range(n)])
B=numpy.array([list(map(int,input().split())) for i in range(n)])
print(A+B)
print(A-B)
print(A*B)
print(A//B)
print(A%B)
print(A**B)

1 4
1 2 3 4
1 2 3 4
[[2 4 6 8]]
[[0 0 0 0]]
[[ 1  4  9 16]]
[[1 1 1 1]]
[[0 0 0 0]]
[[  1   4  27 256]]


In [1]:
#Ques-8 Floor, Ceil and Rint

import numpy
numpy.set_printoptions(legacy='1.13')
A=numpy.array(list(map(float,input().split())))
print(numpy.floor(A))
print(numpy.ceil(A))
print(numpy.rint(A))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [2]:
#Ques-9 Sum and Prod

import numpy
n,m=map(int,input().split())
A=numpy.array([list(map(int,input().split())) for i in range(n)])
print(numpy.prod((numpy.sum(A, axis = 0))))

2 2
1 2
3 4
24


In [3]:
#Ques-10 Min and Max

import numpy
n,m=map(int,input().split())
A=numpy.array([list(map(int,input().split())) for i in range(n)])
print(numpy.max((numpy.min(A, axis = 1))))

2 2
1 2
3 4
3


In [4]:
#Ques-11 Mean Var and Std

import numpy
n,m=map(int,input().split())
A=numpy.array([list(map(int,input().split())) for i in range(n)])
print(numpy.mean(A, axis = 1))
print(numpy.var(A, axis = 0))
print(numpy.std(A, axis=None))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


In [5]:
#Ques-12 Matrix Multiplication

import numpy
n=int(input())
A=numpy.array([list(map(int,input().split())) for i in range(n)])
B=numpy.array([list(map(int,input().split())) for i in range(n)])
print(numpy.dot(A,B))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [6]:
#Ques-13 Inner and Outer Product

import numpy
A=numpy.array([list(map(int,input().split()))])
B=numpy.array([list(map(int,input().split()))])
print(int(numpy.inner(A,B)))
print(numpy.outer(A,B))

1 2
3 4
11
[[3 4]
 [6 8]]


In [7]:
#Ques-14 Polynomials

import numpy
A=list(map(float,input().split()))
B=int(input())
print(numpy.polyval(A,B))

1.1 2 3
0
3.0


In [8]:
#Ques-15 Linear Algebra

import numpy
n=int(input())
A=numpy.array([list(map(float,input().split())) for i in range(n)])
print(numpy.linalg.det(A))

2
1.1 1.1
1.1 1.1
0.0
